### PR TITLE
Fix for truffle testing resolver bug

### LINKED ISSUE #2176: Error: Callback was already called.
- [√] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I have the following error when running solidity test with truffle: 
`Error: Callback was already called.`
I found something similar on the internet here: https://ethereum.stackexchange.com/questions/69406/callback-was-already-called-during-truffle-test-using-a-solidity-testfile

## Steps to Reproduce

When running on the development network `truffle test` of the following contract:
```javascript
pragma solidity ^0.5.10;

import "truffle/Assert.sol";

contract TestUnpackFixed {

  function testUnpackFixed() public {
    uint expectedLength = 1;
    uint a = 1;
    Assert.equal(
      a,
      expectedLength,
      "unpack array length should equal expectedLength");
  }
}
```
truffle-config.js
```javascript
module.exports = {
  networks: {
    development: {
      host: '127.0.0.1',
      port: 7545,
      network_id: '47',
      gas: 4700000,
      gasPrice: 6000000000,
    },
  },

  mocha: {
    reporter: 'eth-gas-reporter',
  },

  compilers: {
    solc: {
      version: '0.5.10',
      settings: {
        optimizer: {
          enabled: true,
          runs: 200,
        },
      },
    },
  },
}
```

## Actual Results

```
➜  yarn truffle test test/TestUnpackFixed.sol
yarn run v1.16.0
$ /Users/andreaspeziale/Repository/.../node_modules/.bin/truffle test test/TestUnpackFixed.sol
Using network 'development'.


Compiling your contracts...
===========================
> Compiling ./test/TestUnpackFixed.sol
> Artifacts written to /var/folders/vn/t04s12zd5dq7h5p30xb8qybw0000gp/T/test-119611-20131-18jjcic.o0o3
> Compiled successfully using:
   - solc: 0.5.10+commit.5a6ea5b1.Emscripten.clang


  TestUnpackFixed
Error: Callback was already called.
    at /Users/andreaspeziale/Repository/.../node_modules/truffle/build/webpack:/packages/truffle-core/~/async/dist/async.js:966:1
    at /Users/andreaspeziale/Repository/.../node_modules/truffle/build/webpack:/packages/truffle-core/~/async/dist/async.js:3885:1
    at <anonymous>
{ _deepCopy: [ 'compilers' ],
  _values:
```

## Environment
```
MacOsX
Truffle v5.0.26 (core: 5.0.26)
Solidity - 0.5.10 (solc-js)
Node v10.16.0
Web3.js v1.0.0-beta.37
```

### PR DESCRIPTION
**Pull request by CruzMolina**
Converts `forEach` to `for...of`.

Resolves #2176.

### CODE REVIEW

File: packages/resolver/fs.js [hunk 1]
```diff
@@ -35,15 +35,17 @@ class FS {
       file => file.match(".json") != null
     );
 
-    filteredBuildArtifacts.forEach(buildArtifact => {
+    for (let i = 0; i < filteredBuildArtifacts.length; i++) {
+      const filename = filteredBuildArtifacts[i];
+
       const artifact = JSON.parse(
-        fs.readFileSync(path.resolve(searchPath, buildArtifact))
+        fs.readFileSync(path.resolve(searchPath, filename))
```
Comment (gnidan) [inline packages/resolver/fs.js]: how is this any different?

Comment (CruzMolina) [reply packages/resolver/fs.js]: not sure, tbh. when rolling back the commits, this seemed to be the culprit. 🤷‍♂

File: packages/resolver/fs.js [hunk 2]
```diff
@@ -35,15 +35,17 @@ class FS {
       file => file.match(".json") != null
     );
 
-    filteredBuildArtifacts.forEach(buildArtifact => {
+    for (let i = 0; i < filteredBuildArtifacts.length; i++) {
```
Comment (gnidan) [inline packages/resolver/fs.js]: let's just do `for (let filename of filterBuildArtifacts) {`
