### PR TITLE
Fix: Ensure provider check duration is shorter than interval frequency

### LINKED ISSUE #3200: Infura project ID request rate exceeded when running tests
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Running `truffle test --network kovan ./test/myTest.js` generates too many calls to `eth_blockNumber` which causes Infura to throw a `project ID request rate exceeded` error.

## Steps to Reproduce

1) Add Infura to your truffle-config.js:
```
const HDWalletProvider = require("@truffle/hdwallet-provider");
const mnemonic = '...'

module.exports = {
  networks: {
    mainnet: {
      provider: () => new HDWalletProvider(mnemonic, "https://mainnet.infura.io/v3/[YOUR_INFURA_API_KEY]"),
      network_id: '1'
    },
    kovan: {
      provider: () => new HDWalletProvider(mnemonic, "https://kovan.infura.io/v3/[YOUR_INFURA_API_KEY]"),
      network_id: '42',
    },
    test: {
      host: "127.0.0.1"
      , port: 7545
      , network_id: '*'
    }
  },
  mocha: {

  },
  compilers: {
    solc: {

    }
  }
}
```

2) Add a test:
```
contract("MyTest", async () => {
    console.log('outer');

    it('should work', () => {
      console.log('inner');
      assert(true);
    });
});
```

3) Run the test: 
`truffle test --network kovan ./test/myTest.js`

## Expected Behavior

The tests should run against contracts on Kovan.

## Actual Results

Sometimes the tests run but more often you get the following:
```
Using network 'kovan'.


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.

/Users/bmac/Desktop/contract_dev/dev/truffle/node_modules/web3-providers-http/src/index.js:96
            callback(error, result);
            ^
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
Error: project ID request rate exceeded
    at /Users/bmac/Desktop/contract_dev/dev/truffle/node_modules/@trufflesuite/web3-provider-engine/subproviders/provider.js:18:36
    at XMLHttpRequest.request.onreadystatechange (/Users/bmac/Desktop/contract_dev/dev/truffle/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/bmac/Desktop/contract_dev/dev/truffle/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/Users/bmac/Desktop/contract_dev/dev/truffle/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/Users/bmac/Desktop/contract_dev/dev/truffle/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/Users/bmac/Desktop/contract_dev/dev/truffle/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at PollingBlockTracker._performSync (/Users/bmac/Desktop/contract_dev/dev/truffle/node_modules/eth-block-tracker/src/polling.js:51:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Looking at the Infura dashboard you see over 100k calls to `eth_blockNumber` after trying to run the tests a just a handfull of times:
Screen Shot

Then you hit the daily limit and you're out of the game for 24 hours:
```
> Something went wrong while attempting to connect to the network. Check your network configuration.

/Users/bmac/Desktop/open_source/virs/node_modules/web3-providers-http/src/index.js:96
            callback(error, result);
            ^
Error: daily request count exceeded, request rate limited
    at /Users/bmac/Desktop/open_source/virs/node_modules/@trufflesuite/web3-provider-engine/subproviders/provider.js:18:36
    at XMLHttpRequest.request.onreadystatechange (/Users/bmac/Desktop/open_source/virs/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/bmac/Desktop/open_source/virs/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/Users/bmac/Desktop/open_source/virs/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/Users/bmac/Desktop/open_source/virs/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/Users/bmac/Desktop/open_source/virs/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

## Environment

* Operating System: macOS Catalina (10.15.2)
* Ethereum client: n/a
* Truffle version (`truffle version`): v5.1.35 (core: 5.1.35)
* node version (`node --version`): v10.16.3
* npm version (`npm --version`): 6.9.0

### PR DESCRIPTION
**Pull request by CruzMolina**
Implements provider check with exponential backoff using a recursive `setTimeout` pattern.

Resolves #3200.

### CODE REVIEW

File: packages/provider/index.js [hunk 1]
```diff
@@ -56,24 +56,29 @@ module.exports = {
...
+                  "to the network. Check your network configuration."
+              );
+              clearTimeout(noResponseFromNetworkCall);
+              clearTimeout(networkCheck);
+              reject(error);
+            });
+          networkCheckDelay *= 2;
+          networkCheck();
+        }, networkCheckDelay);
+      })();
```
Comment (gnidan) [inline packages/provider/index.js:81]: this is getting unwieldy, can we make it an async func?
