### PR TITLE
Enhancement: Extend timeout override polling logic

### LINKED ISSUE #1575: "Migrations" -- The contract code couldn't be stored, please check your gas limit..
- [ X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Trying to deploy a contract to mainnet, once Truffle tries to deploy the migrations it fails with the message 

    "Migrations" -- The contract code couldn't be stored, please check your gas limit..

    at /home/patric/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:364:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

My truffle.js settings:

         main: {
            gas: 8000000,
            provider: function() {
                return new HDWalletProvider('', "https://mainnet.infura.io/v3/apikey")
            },
            network_id: "*"
        },

 the contract gets mined successfully though

## Expected Behavior

Contract gets deployed successfully

## Actual Results

migrations fails

## Environment

* Operating System: Linux Mint
* Ethereum client: infura
Truffle v5.0.0-beta.2 (core: 5.0.0-beta.2)
Solidity v0.5.0 (solc-js)
Node v8.14.0
* npm version (`npm --version`): 6.4.1

### PR DESCRIPTION
**Pull request by CruzMolina**
- Include default Web3 error message as part of
contract deployment error handling
- Ignore default Web3 error message only when setting
a custom default block timeout greater than Web3's default (50)
- Ensure promievent receipt is fired when override logic
successfully returns a tx receipt
- Add test util method & test case for simulating tx propagation
 delays when deploying contracts via live network gateways
(Infura, Cloudflare, etc)

Using the [reproduction steps](https://github.com/trufflesuite/truffle/issues/2257#issuecomment-558919818) outlined in #2257 against this branch locally, it appears I have been able to overcome the gateway tx delays [discussed](https://github.com/trufflesuite/truffle/issues/1575#issuecomment-579560921) in #1575.

This is a short-term solution that neither adds a new flag or config option that users need to enable, nor requires building out completely new custom logic. Instead, it hooks into & extends the currently existing architecture and an already existent deployment config option.

It would be nice for this behavior to be default, but unfortunately Web3 appears to throw a generic error message whenever there is some JSON response it doesn't know how to handle. This makes it difficult to know when and where exactly it is running into this very specific issue (gateway tx propagation delay). 

Example usage:

```javascript
// truffle-config.js
module.exports = {
  networks: {
    ...
    goerli: {
      ...
      timeoutBlocks: 60 // must be greater than Web3's default (50)
    }
  }
};
```

Aims to resolve #1575 & #2257.

As an aside, there is possibly a fix in here for general `timeoutBlock` usage. It appears the current override logic was never hooked up to fire a receipt promievent to the reporter upon successfully returning a tx receipt. This was making actual migrations crash when smoke testing locally.

### CODE REVIEW

File: packages/contract/lib/override.js [hunk 1]
```diff
@@ -42,9 +43,12 @@ const override = {
     const timedOut =
       web3Error.message && web3Error.message.includes(override.timeoutMessage);
     const shouldWait = maxBlocks > currentBlock;
+    const waitForTxPropagation =
+      web3Error.message &&
+      web3Error.message.includes(override.defaultWeb3Error);
 
     // Reject after attempting to get reason string if we shouldn't be waiting.
-    if (!timedOut || !shouldWait) {
+    if (!shouldWait && (!timedOut || !waitForTxPropagation)) {
```
Comment (gnidan) [inline packages/contract/lib/override.js]: Minor comment: could we make this logic just defer to the function in handlers?

**Comment by CruzMolina** [comment]
Thanks for the review @gnidan !
